title = "RBXRankDB"  # From Git
gitRepoUrl = "https://github.com/123marble/RBXRankDB" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
# favicon = ""

# From git:
organizationName = "123marble"
projectName = "RankStore"
url = "https://123marble.github.io"
baseUrl = "/RBXRankDB"
tagline = "RBX Client for RankDB"

[footer]
style = "dark"
copyright = "Copyright Â© 2021 AuthorName. Built with Moonwave and Docusaurus"